=== ccbunao/vector_ap_bsw/em/etc/application_manifest_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Schema for the JSON representation of application manifest files",
    "definitions": {
        "machineModePrototype": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "string"
            }
        }
    },
    "type": "object",
    "required": [
        "category",
        "name",
        "processes"
    ],
    "properties": {
        "category": {
            "type": "string",
            "enum": [
                "APPLICATION_LEVEL",
                "PLATFORM_LEVEL"
            ]
        },
        "name": {
            "type": "string"
        },
        "isAdaptiveApplication": {
            "type": "integer"
        },
        "processes": {
            "type": "array",
            "items": {
                "type": "object",
                "maxProperties": 2,
                "required": [
                    "name",
                    "startupConfigs"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "startupConfigs": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "schedulingPolicy",
                                "schedulingPriority",
                                "machineStates"
                            ],
                            "properties": {
                                "schedulingPolicy": {
                                    "type": "string",
                                    "enum": [
                                        "SCHEDULING-POLICY-OTHER",
                                        "SCHEDULING-POLICY-FIFO",
                                        "SCHEDULING-POLICY-ROUND-ROBIN"
                                    ]
                                },
                                "schedulingPriority": {
                                    "type": "integer"
                                },
                                "machineStates": {
                                    "$ref": "#/definitions/machineModePrototype"
                                },
                                "functionGroups": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "states": {
                                                "$ref": "#/definitions/machineModePrototype"
                                            }
                                        }
                                    }
                                },
                                "options": {
                                    "type": "array",
                                    "minItems": 0,
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "executionDependency": {
                                    "type": "object",
                                    "minProperties": 0,
                                    "additionalProperties": {
                                        "type": "integer"
                                    }
                                },
                                "cores": {
                                    "type": "object",
                                    "maxProperties": 2,
                                    "properties": {
                                        "shallRunOn": {
                                            "type": "array",
                                            "minItems": 0,
                                            "items": {
                                                "type": "integer"
                                            }
                                        },
                                        "shallNotRunOn": {
                                            "type": "array",
                                            "minItems": 0,
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    },
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== ccbunao/vector_ap_bsw/em/addon/amsr-vector-fs-em-executionmanager-demo-application/etc/manifest2.json
{
  "category": "APPLICATION_LEVEL",
  "name": "amsr-vector-fs-em-executionmanager-demo-application2",
  "isAdaptiveApplication": 1,
  "processes": [
    {
      "name": "amsr-vector-fs-em-executionmanager-demo-application2",
      "startupConfigs": [
        {
          "schedulingPolicy": "SCHEDULING-POLICY-FIFO",
          "schedulingPriority": 40,
          "options": [
            "Option1",
            "Option2"
          ],
          "executionDependency": {
            "em-demo-process": 1
          },
          "machineStates": [
            "Startup",
            "Running"
          ],
          "cores": {
            "shallNotRunOn": [
              2
            ],
            "shallRunOn": [
              3
            ]
          }
        },
        {
          "schedulingPolicy": "SCHEDULING-POLICY-ROUND-ROBIN",
          "schedulingPriority": 40,
          "options": [],
          "executionDependency": {},
          "machineStates": [
            "Running"
          ],
          "cores": {
            "shallNotRunOn": [
              2,
              3
            ],
            "shallRunOn": [
              1
            ]
          }
        }
      ]
    }
  ]
}

=== ccbunao/vector_ap_bsw/amsr-vector-fs-em-executionmanager/addon/amsr-vector-fs-em-executionmanager-demo-application/etc/manifest3.json
{
  "category": "APPLICATION_LEVEL",
  "name": "amsr-vector-fs-em-executionmanager-demo-application3",
  "isAdaptiveApplication": 1,
  "processes": [
    {
      "name": "amsr-vector-fs-em-executionmanager-demo-application3",
      "startupConfigs": [
        {
          "schedulingPolicy": "SCHEDULING-POLICY-FIFO",
          "schedulingPriority": 40,
          "options": [
            "Option1",
            "Option2"
          ],
          "executionDependency": {
            "em-demo-process": 1
          },
          "machineStates": [
            "Startup",
            "Running"
          ],
          "cores": {
            "shallNotRunOn": [
              2
            ],
            "shallRunOn": [
              3
            ]
          }
        }
      ]
    }
  ]
}
